name: verify project

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

    - name: Install composer dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install phive
      run: wget -O phive https://phar.io/releases/phive.phar

    - name: Gives phive execution right
      run: chmod u+x phive

    - name: Cache phive packages
      id: phive-tools-cache
      uses: actions/cache@v2
      with:
        path: tools
        key: ${{ runner.os }}-phive-packages-${{ hashFiles('**/phive.xml') }}1

    - name: Install phive dependencies
      if: steps.phive-tools-cache.outputs.cache-hit != 'true'
      run: ./phive install --trust-gpg-keys 4AA394086372C20A phpunit && chmod u+x ./tools/phpunit

    - uses: actions/upload-artifact@v2
      with:
        name: installed-project
        path: ./

  test:
    needs: install
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: installed-project

    - name: Display structure of downloaded files
      run: ls -R

    - name: Run PHPUnit test
      run: ./tools/phpunit -c ./build/phpunit.xml
